using System;
using System.IO;
using System.Text;
using YamlDotNet.RepresentationModel;

namespace dotnetCampus.YamlToCSharp
{
    /// <summary>
    /// 将 Yaml 文件转换为 CSharp 文件
    /// </summary>
    public class YamlFileToCSharpFile
    {
        /// <summary>
        /// 将 Yaml 文件转换为 CSharp 文件
        /// </summary>
        /// <param name="yamlFile"></param>
        /// <param name="saveCSharpFile"></param>
        /// <param name="classNamespace">类命名空间</param>
        /// <param name="interfaceName">继承的接口</param>
        /// <param name="className">类名</param>
        /// <param name="methodName"></param>
        public void ParseToCSharpFile(FileInfo yamlFile, FileInfo saveCSharpFile,
            string classNamespace = "dotnetCampus.Localizations",
            string interfaceName = "",
            string className = "",
            string methodName = "GetLang")
        {
            var yaml = new YamlStream();

            yaml.Load(new StringReader(File.ReadAllText(yamlFile.FullName)));

            var yamlToCSharpDictionary = new YamlToCSharpDictionary();
            var dictionary = yamlToCSharpDictionary.ParseToCSharp(yaml);

            if (string.IsNullOrEmpty(className))
            {
                className = Path.GetFileNameWithoutExtension(saveCSharpFile.FullName);
            }

            if (!string.IsNullOrEmpty(interfaceName))
            {
                if (!interfaceName.StartsWith(":"))
                {
                    interfaceName = $": {interfaceName}";
                }
            }

            var str = $@"//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace {classNamespace}
{{
    [System.CodeDom.Compiler.GeneratedCode(""dotnetCampus.YamlToCSharp"", ""1.0.0"")]
    public class {className} {interfaceName}
    {{
        public Dictionary<string, string> {methodName}()
        {{
            return {dictionary};
        }}
    }}
}}";

            Directory.CreateDirectory(saveCSharpFile.DirectoryName);
            TryToWriteFile(saveCSharpFile, str);
        }

        private void TryToWriteFile(FileInfo saveCSharpFile, string str)
        {
            if (File.Exists(saveCSharpFile.FullName))
            {
                var nextText = str.Replace("\r", "");
                var oldText = File.ReadAllText(saveCSharpFile.FullName);
                oldText = oldText.Replace("\r", "");
                if (oldText == nextText)
                {
                    Console.WriteLine("文件没有改变，不需要写入");
                    return;
                }
            }

            File.WriteAllText(saveCSharpFile.FullName, str, Encoding.UTF8);
        }
    }
}